function onCreate()
    makeLuaSprite('bg', 'mod-bgs/world1/bg', -1200, -500)
    makeLuaSprite('floor', 'mod-bgs/world1/floor', -1200, -500)
    makeLuaSprite('speakers', 'mod-bgs/world1/speakers', -1340, -590)
    makeAnimatedLuaSprite('beat1', 'mod-bgs/beatAnim', 162, 734)
    makeAnimatedLuaSprite('beat2', 'mod-bgs/beatAnim', 394, 691)
    makeAnimatedLuaSprite('beat3', 'mod-bgs/beatAnim', 390, 485)
    makeAnimatedLuaSprite('beat4', 'mod-bgs/beatAnim', 675, 700)
    addAnimationByPrefix('beat1', 'boop', 'boop', curBpm/2, false)
    addAnimationByPrefix('beat2', 'boop', 'boop', curBpm/2, false)
    addAnimationByPrefix('beat3', 'boop', 'boop', curBpm/2, false)
    addAnimationByPrefix('beat4', 'boop', 'boop', curBpm/2, false)
    scaleObject('bg', 1.25, 1.25)
    scaleObject('floor', 1.25, 1.25)
    scaleObject('speakers', 1.35, 1.35)
    scaleObject('beat1', 1.25, 1.25)
    scaleObject('beat2', 1.65, 1.65)
    scaleObject('beat3', 1.65, 1.65)
    scaleObject('beat4', 1.55, 1.55)
    addLuaSprite('bg')
    addLuaSprite('floor')
    addLuaSprite('speakers')
    addLuaSprite('beat1')
    addLuaSprite('beat2')
    addLuaSprite('beat3')
    addLuaSprite('beat4')
end

function onCountdownTick(counter)
    if counter == 4 then
        objectPlayAnimation('beat1', 'boop', true)
        objectPlayAnimation('beat2', 'boop', true)
        objectPlayAnimation('beat3', 'boop', true)
        objectPlayAnimation('beat4', 'boop', true)
    end
end

function onBeatHit()
    objectPlayAnimation('beat1', 'boop', true)
    objectPlayAnimation('beat2', 'boop', true)
    objectPlayAnimation('beat3', 'boop', true)
    objectPlayAnimation('beat4', 'boop', true)
end
